server:
  port: 9000

eureka:
#  server:
#    enable-self-preservation: false
#    eviction-interval-timer-in-ms: 4000
  instance:
    hostname: localhost
#    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://localhost:9000/eureka/
spring:
  application:
    name: eureka
